<?php

declare(strict_types=1);

namespace PlotBox\Standards\Command;

use PlotBox\Standards\Util\Util;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

use function Safe\file_get_contents;
use function Safe\file_put_contents;
use function Safe\mkdir;

final class CompileAiGuidance extends Command
{
    private const string COMMAND_NAME = 'compile-ai-guidance';

    private const string CURSOR_RULES_FILE = '.cursor/rules/all.mdc';
    private const string JUNIE_GUIDELINES_FILE = '.junie/guidelines.md';

    /**
     * @param array<int, string> $modules
     */
    public function __construct(
        private readonly array $modules = ['GENERAL', 'PHP']
    ) {
        parent::__construct();
    }

    /** @inheritDoc */
    protected function configure(): void
    {
        $this
            ->setName(self::COMMAND_NAME)
            ->setDescription('Compiles AI guidance files for Cursor and Junie from source guidance files');
    }

    /** @inheritDoc */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $projectRoot = Util::getProjectRoot();
        chdir($projectRoot);

        if (!file_exists('REPO_GUIDANCE.md')) {
            $output->writeln('<error>REPO_GUIDANCE.md not found in project root. Aborting.</error>');
            return Command::FAILURE;
        }

        $combinedContent = $this->getCombinedContent($projectRoot);

        $this->writeCursorRules($projectRoot, $combinedContent, $output);
        $this->writeJunieGuidelines($projectRoot, $combinedContent, $output);

        $output->writeln('<info>AI guidance files compiled successfully!</info>');

        return Command::SUCCESS;
    }

    private function getCombinedContent(string $projectRoot): string
    {
        $sourceFiles = ['REPO_GUIDANCE.md'];
        foreach ($this->modules as $module) {
            $module = strtoupper($module);
            $vendorPath = "vendor/plotbox-io/standards/guidance/$module.md";
            $localPath = "guidance/$module.md";

            if (file_exists($projectRoot . '/' . $vendorPath)) {
                $sourceFiles[] = $vendorPath;
            } elseif (file_exists($projectRoot . '/' . $localPath)) {
                $sourceFiles[] = $localPath;
            }
        }

        $content = '';
        foreach ($sourceFiles as $file) {
            $path = $projectRoot . '/' . $file;
            if (file_exists($path)) {
                $content .= "## Source: $file\n\n";
                $content .= file_get_contents($path) . "\n\n";
            }
        }
        return $content;
    }

    private function writeCursorRules(
        string $projectRoot,
        string $content,
        OutputInterface $output
    ): void {
        $path = $projectRoot . '/' . self::CURSOR_RULES_FILE;
        $directory = dirname($path);
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $warning = "<!--\nDO NOT EDIT THIS FILE DIRECTLY.\n";
        $warning .= "It is generated from REPO_GUIDANCE.md and vendor/plotbox-io/standards/guidance/ files.\n";
        $warning .= "Run 'bin/dev compile-ai-guidance' to regenerate.\n-->\n\n";

        $frontmatter = "---\nglobs: **/*\nalwaysApply: false\n---\n";

        file_put_contents($path, $frontmatter . $warning . $content);
        $output->writeln("<comment>Updated $path</comment>");
    }

    private function writeJunieGuidelines(
        string $projectRoot,
        string $content,
        OutputInterface $output
    ): void {
        $path = $projectRoot . '/' . self::JUNIE_GUIDELINES_FILE;
        $directory = dirname($path);
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $warning = "<!--\nDO NOT EDIT THIS FILE DIRECTLY.\n";
        $warning .= "It is generated from REPO_GUIDANCE.md and vendor/plotbox-io/standards/guidance/ files.\n";
        $warning .= "Run 'bin/dev compile-ai-guidance' to regenerate.\n-->\n\n";

        file_put_contents($path, $warning . $content);
        $output->writeln("<comment>Updated $path</comment>");
    }
}
